create table IF NOT EXISTS original_link
(
    id       bigint generated by default as identity
        primary key,
    original varchar(1000) not null
        constraint uk_q8b5f9l6apt2x4bq56nc9tut4
            unique
);

create table IF NOT EXISTS short_link
(
    id               bigint generated by default as identity
        primary key,
    link             varchar(255) not null
        constraint uk_qhuvlunb4kmuffex9yr3jnsd8
            unique,
    original_link_id bigint
        constraint fk2pmvgl69ucohui2n0iybtlkrs
            references original_link
);

create table IF NOT EXISTS stat
(
    id         bigint generated by default as identity
        primary key,
    count      bigint       not null,
    short_link varchar(255) not null
);